COUNTRY = ({
    "Philippines": {
        "optimal_orientation": "South",
        "efficiency": 90,
        "inclination": "10°-15°",
        "harvest_length": 6,
        "solar_irradiance": 5.0,
        "AC": 230,
        "HZ": 60,
        "seasonal_period": "Year-round",
        "weather_conditions": "Tropical, with rainy season from June to November"
    },
    "USA": {
        "optimal_orientation": "South",
        "efficiency": 100,
        "inclination": "30°-40°",
        "harvest_length": 5.5,
        "solar_irradiance": 5.5,
        "AC": 120,
        "HZ": 60,
        "seasonal_period": "Year-round",
        "weather_conditions": "Mild, with occasional snow in winter"
    },
    "Mexico": {
        "optimal_orientation": "South",
        "efficiency": 100,
        "inclination": "20°-25°",
        "harvest_length": 5.5,
        "solar_irradiance": 5.6,
        "AC": 127,
        "HZ": 60,
        "seasonal_period": "Year-round",
        "weather_conditions": "Hot summers, mild winters"
    },
    "UK": {
        "optimal_orientation": "South",
        "efficiency": 90,
        "inclination": "20°-30°",
        "harvest_length": 4.5,
        "solar_irradiance": 3.2,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Summer",
        "weather_conditions": "Cloudy and rainy, occasional sunshine"
    },
    "Italy": {
        "optimal_orientation": "South",
        "efficiency": 95,
        "inclination": "25°-35°",
        "harvest_length": 5.0,
        "solar_irradiance": 4.8,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Summer",
        "weather_conditions": "Mild climate, sunny in summer"
    },
    "Spain": {
        "optimal_orientation": "South",
        "efficiency": 100,
        "inclination": "30°-40°",
        "harvest_length": 5.5,
        "solar_irradiance": 5.0,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Year-round",
        "weather_conditions": "Sunny and dry, especially in southern areas"
    },
    "France": {
        "optimal_orientation": "South",
        "efficiency": 95,
        "inclination": "25°-35°",
        "harvest_length": 5.0,
        "solar_irradiance": 4.2,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Summer",
        "weather_conditions": "Moderate climate, sunny in the summer"
    },
    "South Africa": {
        "optimal_orientation": "North",
        "efficiency": 95,
        "inclination": "25°-30°",
        "harvest_length": 6,
        "solar_irradiance": 5.5,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Year-round",
        "weather_conditions": "Sunny and dry, with occasional storms"
    },
    "Egypt": {
        "optimal_orientation": "South",
        "efficiency": 100,
        "inclination": "10°-15°",
        "harvest_length": 6,
        "solar_irradiance": 5.8,
        "AC": 220,
        "HZ": 50,
        "seasonal_period": "Year-round",
        "weather_conditions": "Hot desert climate with very little rain"
    },
    "Argentina": {
        "optimal_orientation": "North",
        "efficiency": 90,
        "inclination": "15°-25°",
        "harvest_length": 5.5,
        "solar_irradiance": 5.3,
        "AC": 220,
        "HZ": 50,
        "seasonal_period": "Year-round",
        "weather_conditions": "Temperate with occasional storms and dry periods"
    },
    "Chile": {
        "optimal_orientation": "North",
        "efficiency": 95,
        "inclination": "20°-30°",
        "harvest_length": 5.5,
        "solar_irradiance": 5.6,
        "AC": 220,
        "HZ": 50,
        "seasonal_period": "Year-round",
        "weather_conditions": "Arid and sunny, with some rainfall in the south"
    },
    "Turkey": {
        "optimal_orientation": "South",
        "efficiency": 95,
        "inclination": "25°-35°",
        "harvest_length": 6,
        "solar_irradiance": 5.0,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Year-round",
        "weather_conditions": "Mild, with Mediterranean climate in the coastal areas"
    },
    "Greece": {
        "optimal_orientation": "South",
        "efficiency": 100,
        "inclination": "25°-35°",
        "harvest_length": 5.5,
        "solar_irradiance": 5.2,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Year-round",
        "weather_conditions": "Mediterranean climate with hot summers and mild winters"
    },
    "Portugal": {
        "optimal_orientation": "South",
        "efficiency": 100,
        "inclination": "25°-35°",
        "harvest_length": 5.5,
        "solar_irradiance": 5.0,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Year-round",
        "weather_conditions": "Mediterranean climate with warm summers"
    },
    "Russia": {
        "optimal_orientation": "South",
        "efficiency": 90,
        "inclination": "20°-30°",
        "harvest_length": 4.5,
        "solar_irradiance": 3.5,
        "AC": 220,
        "HZ": 50,
        "seasonal_period": "Spring-Summer",
        "weather_conditions": "Cold winters, with hot summers in the southern regions"
    },
    "China": {
        "optimal_orientation": "South",
        "efficiency": 95,
        "inclination": "15°-25°",
        "harvest_length": 5.0,
        "solar_irradiance": 4.8,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Year-round",
        "weather_conditions": "Varied climate, with hot summers and cold winters in northern areas"
    },
    "Vietnam": {
        "optimal_orientation": "South",
        "efficiency": 90,
        "inclination": "10°-20°",
        "harvest_length": 6,
        "solar_irradiance": 5.0,
        "AC": 220,
        "HZ": 50,
        "seasonal_period": "Year-round",
        "weather_conditions": "Tropical, with wet and dry seasons"
    },
    "Malaysia": {
        "optimal_orientation": "West",
        "efficiency": 90,
        "inclination": "10°-20°",
        "harvest_length": 6,
        "solar_irradiance": 5.5,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Year-round",
        "weather_conditions": "Tropical with heavy rainfall and sunny periods"
    },
    "Singapore": {
        "optimal_orientation": "South",
        "efficiency": 100,
        "inclination": "10°-20°",
        "harvest_length": 6,
        "solar_irradiance": 5.2,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Year-round",
        "weather_conditions": "Tropical with high humidity and occasional rain"
    },
    "Brazil": {
        "optimal_orientation": "North",
        "efficiency": 95,
        "inclination": "20°-30°",
        "harvest_length": 6,
        "solar_irradiance": 5.0,
        "AC": 220,
        "HZ": 50,
        "seasonal_period": "Year-round",
        "weather_conditions": "Tropical and subtropical, with heavy rains in the north"
    },
    "India": {
        "optimal_orientation": "South",
        "efficiency": 90,
        "inclination": "10°-20°",
        "harvest_length": 6,
        "solar_irradiance": 5.5,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Year-round",
        "weather_conditions": "Tropical with hot summers and monsoon rains"
    },
    "Thailand": {
        "optimal_orientation": "South",
        "efficiency": 90,
        "inclination": "10°-20°",
        "harvest_length": 6,
        "solar_irradiance": 5.2,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Year-round",
        "weather_conditions": "Tropical, with a wet and dry season"
    },
    "Indonesia": {
        "optimal_orientation": "South",
        "efficiency": 90,
        "inclination": "10°-20°",
        "harvest_length": 6,
        "solar_irradiance": 5.3,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Year-round",
        "weather_conditions": "Tropical climate, with occasional rains"
    },
    "Nigeria": {
        "optimal_orientation": "South",
        "efficiency": 95,
        "inclination": "15°-25°",
        "harvest_length": 6,
        "solar_irradiance": 5.0,
        "AC": 220,
        "HZ": 50,
        "seasonal_period": "Year-round",
        "weather_conditions": "Tropical, with some dry and rainy seasons"
    },
    "Kenya": {
        "optimal_orientation": "North",
        "efficiency": 95,
        "inclination": "20°-30°",
        "harvest_length": 6,
        "solar_irradiance": 5.2,
        "AC": 240,
        "HZ": 50,
        "seasonal_period": "Year-round",
        "weather_conditions": "Tropical with dry and wet seasons"
    },
    "Australia": {
        "optimal_orientation": "North",
        "efficiency": 100,
        "inclination": "30°-40°",
        "harvest_length": 6.5,
        "solar_irradiance": 5.4,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Year-round",
        "weather_conditions": "Sunny and dry in most regions, coastal areas have moderate temperatures"
    },
    "New Zealand": {
        "optimal_orientation": "North",
        "efficiency": 90,
        "inclination": "30°-40°",
        "harvest_length": 6,
        "solar_irradiance": 4.9,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Year-round",
        "weather_conditions": "Temperate with moderate sunshine"
    },
    "Canada": {
        "optimal_orientation": "South",
        "efficiency": 85,
        "inclination": "40°-50°",
        "harvest_length": 4,
        "solar_irradiance": 3.8,
        "AC": 120,
        "HZ": 60,
        "seasonal_period": "Spring-Fall",
        "weather_conditions": "Cold winters, mild summers with sunny periods"
    },
    "United Kingdom": {
        "optimal_orientation": "South",
        "efficiency": 85,
        "inclination": "30°-40°",
        "harvest_length": 4.5,
        "solar_irradiance": 3.6,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Summer",
        "weather_conditions": "Cool, cloudy weather with a high level of rainfall"
    },
    "Germany": {
        "optimal_orientation": "South",
        "efficiency": 90,
        "inclination": "30°-40°",
        "harvest_length": 4.5,
        "solar_irradiance": 3.8,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Summer",
        "weather_conditions": "Moderate climate, with frequent rainfall"
    },
    "Sweden": {
        "optimal_orientation": "South",
        "efficiency": 85,
        "inclination": "35°-45°",
        "harvest_length": 4,
        "solar_irradiance": 3.5,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Summer",
        "weather_conditions": "Cold winters and mild summers, with long days in summer"
    },
    "Norway": {
        "optimal_orientation": "South",
        "efficiency": 85,
        "inclination": "35°-45°",
        "harvest_length": 4,
        "solar_irradiance": 3.4,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Summer",
        "weather_conditions": "Cold winters and cool summers"
    },
    "South Korea": {
        "optimal_orientation": "South",
        "efficiency": 90,
        "inclination": "20°-30°",
        "harvest_length": 5,
        "solar_irradiance": 5.0,
        "AC": 220,
        "HZ": 60,
        "seasonal_period": "Year-round",
        "weather_conditions": "Temperate climate with four distinct seasons"
    },
    "Japan": {
        "optimal_orientation": "South",
        "efficiency": 85,
        "inclination": "20°-30°",
        "harvest_length": 5,
        "solar_irradiance": 4.7,
        "AC": 100,
        "HZ": "50 Hz (East) / 60 Hz (West)",
        "seasonal_period": "Year-round",
        "weather_conditions": "Tropical and temperate with humid summers"
    },
"Colombia": {
        "optimal_orientation": "South",
        "efficiency": 95,
        "inclination": "10°-20°",
        "harvest_length": 6,
        "solar_irradiance": 5.3,
        "AC": 110,
        "HZ": 60,
        "seasonal_period": "Year-round",
        "weather_conditions": "Tropical with a rainy and dry season"
    },
    "Peru": {
        "optimal_orientation": "South",
        "efficiency": 95,
        "inclination": "15°-25°",
        "harvest_length": 6,
        "solar_irradiance": 5.5,
        "AC": 220,
        "HZ": 50,
        "seasonal_period": "Year-round",
        "weather_conditions": "Tropical with a wet season from November to March"
    },
    "Finland": {
        "optimal_orientation": "South",
        "efficiency": 85,
        "inclination": "35°-45°",
        "harvest_length": 3.5,
        "solar_irradiance": 3.1,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Summer",
        "weather_conditions": "Cold winters and short, cool summers"
    },
    "Iceland": {
        "optimal_orientation": "South",
        "efficiency": 80,
        "inclination": "40°-50°",
        "harvest_length": 3,
        "solar_irradiance": 2.8,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Summer",
        "weather_conditions": "Cold, with very short days in winter"
    },
    "Belgium": {
        "optimal_orientation": "South",
        "efficiency": 90,
        "inclination": "30°-40°",
        "harvest_length": 4.5,
        "solar_irradiance": 3.5,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Summer",
        "weather_conditions": "Mild winters and rainy, cool summers"
    },
    "Netherlands": {
        "optimal_orientation": "South",
        "efficiency": 85,
        "inclination": "30°-40°",
        "harvest_length": 4.0,
        "solar_irradiance": 3.3,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Summer",
        "weather_conditions": "Mild winters and cool, rainy summers"
    },
"Ukraine": {
        "optimal_orientation": "South",
        "efficiency": 90,
        "inclination": "30°-40°",
        "harvest_length": 4.5,
        "solar_irradiance": 3.7,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Fall",
        "weather_conditions": "Cold winters, hot summers"
    },
    "Hungary": {
        "optimal_orientation": "South",
        "efficiency": 95,
        "inclination": "25°-35°",
        "harvest_length": 5.0,
        "solar_irradiance": 4.1,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Fall",
        "weather_conditions": "Moderate with hot summers and cold winters"
    },
    "Slovakia": {
        "optimal_orientation": "South",
        "efficiency": 90,
        "inclination": "30°-40°",
        "harvest_length": 4.5,
        "solar_irradiance": 3.8,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Summer",
        "weather_conditions": "Cold winters, mild summers"
    },
    "Croatia": {
        "optimal_orientation": "South",
        "efficiency": 95,
        "inclination": "25°-35°",
        "harvest_length": 5.0,
        "solar_irradiance": 4.3,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Summer",
        "weather_conditions": "Mediterranean climate with hot summers"
    },
    "Serbia": {
        "optimal_orientation": "South",
        "efficiency": 95,
        "inclination": "25°-35°",
        "harvest_length": 5.0,
        "solar_irradiance": 4.2,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Fall",
        "weather_conditions": "Warm summers and cold winters"
    },
    "Bulgaria": {
        "optimal_orientation": "South",
        "efficiency": 95,
        "inclination": "25°-35°",
        "harvest_length": 5.0,
        "solar_irradiance": 4.4,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Summer",
        "weather_conditions": "Warm, sunny summers with cold winters"
    },
    "Lithuania": {
        "optimal_orientation": "South",
        "efficiency": 85,
        "inclination": "30°-40°",
        "harvest_length": 4.0,
        "solar_irradiance": 3.6,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Summer",
        "weather_conditions": "Cold winters, mild summers"
    },
    "Montenegro": {
        "optimal_orientation": "South",
        "efficiency": 95,
        "inclination": "25°-35°",
        "harvest_length": 5.0,
        "solar_irradiance": 4.3,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Summer",
        "weather_conditions": "Mild winters, warm summers"
    },
    "Macedonia": {
        "optimal_orientation": "South",
        "efficiency": 90,
        "inclination": "20°-30°",
        "harvest_length": 5.0,
        "solar_irradiance": 4.0,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Fall",
        "weather_conditions": "Cold winters, warm summers"
    },
    "Kosovo": {
        "optimal_orientation": "South",
        "efficiency": 90,
        "inclination": "25°-35°",
        "harvest_length": 5.0,
        "solar_irradiance": 4.0,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Fall",
        "weather_conditions": "Cold winters, hot summers"
    },
    "North Macedonia": {
        "optimal_orientation": "South",
        "efficiency": 90,
        "inclination": "20°-30°",
        "harvest_length": 5.0,
        "solar_irradiance": 4.1,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Fall",
        "weather_conditions": "Mild winters and hot summers"
    },
    "Latvia": {
        "optimal_orientation": "South",
        "efficiency": 85,
        "inclination": "30°-40°",
        "harvest_length": 4.0,
        "solar_irradiance": 3.5,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Summer",
        "weather_conditions": "Cold winters, cool summers"
    },
    "Estonia": {
        "optimal_orientation": "South",
        "efficiency": 80,
        "inclination": "30°-40°",
        "harvest_length": 3.5,
        "solar_irradiance": 3.3,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Summer",
        "weather_conditions": "Cold winters, mild summers"
    },
    "Poland": {
        "optimal_orientation": "South",
        "efficiency": 90,
        "inclination": "30°-40°",
        "harvest_length": 4.0,
        "solar_irradiance": 3.8,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Summer",
        "weather_conditions": "Cold winters, mild summers"
    },
    "Czech Republic": {
        "optimal_orientation": "South",
        "efficiency": 90,
        "inclination": "30°-40°",
        "harvest_length": 4.5,
        "solar_irradiance": 3.9,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Summer",
        "weather_conditions": "Cold winters, mild summers"
    },
    "Slovenia": {
        "optimal_orientation": "South",
        "efficiency": 95,
        "inclination": "25°-35°",
        "harvest_length": 5.0,
        "solar_irradiance": 4.0,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Summer",
        "weather_conditions": "Mild summers, cold winters"
    },
    "Romania": {
        "optimal_orientation": "South",
        "efficiency": 90,
        "inclination": "25°-35°",
        "harvest_length": 4.5,
        "solar_irradiance": 3.7,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Fall",
        "weather_conditions": "Cold winters, hot summers"
    },
    "Moldova": {
        "optimal_orientation": "South",
        "efficiency": 90,
        "inclination": "30°-40°",
        "harvest_length": 4.5,
        "solar_irradiance": 3.6,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Summer",
        "weather_conditions": "Cold winters, warm summers"
    },
    "Albania": {
        "optimal_orientation": "South",
        "efficiency": 95,
        "inclination": "25°-35°",
        "harvest_length": 5.0,
        "solar_irradiance": 4.1,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Year-round",
        "weather_conditions": "Mediterranean climate with hot, dry summers"
    },
    "Bosnia and Herzegovina": {
        "optimal_orientation": "South",
        "efficiency": 95,
        "inclination": "25°-35°",
        "harvest_length": 5.0,
        "solar_irradiance": 4.0,
        "AC": 230,
        "HZ": 50,
        "seasonal_period": "Spring-Summer",
        "weather_conditions": "Mild climate, hot summers"
    }
})
